/* Phase 3 library — healthy South Indian, Gujarati, Punjabi, North Indian and fusion recipes.
   Same per-serving format as recipes.js. Shared-base chicken dishes carry
   protein:{veg:[food,qty,unit,label], chicken:[food,qty,unit,label]} — one gravy, two proteins:
   Akshar & Aum get chicken, Dvija gets the veg protein (and everyone gets veg on Thu/Sat). */
RECIPES.push(
  /* ======================= BREAKFASTS ======================= */
  // South Indian
  RC({id:'idli',name:'Idli Sambar + Boiled Eggs',cat:'breakfast',cuisine:'South Indian',tags:['idli','sambar','egg','steamed'],
    upgrade:'Steamed, fermented and paired with lentil sambar and eggs.',
    ing:[['dosabatter',130,'g'],['toor',25,'g'],['mixveg',50,'g'],['egg',2,''],['oil',3,'g']],
    serve:[[3,'','idli'],[150,'ml','sambar'],[2,'','boiled eggs']],
    method:['Steam the idlis in greased moulds for 10–12 minutes (Instant Pot steam setting works).','Pressure-cook toor dal; simmer with vegetables, tamarind and sambar powder; temper with mustard and curry leaves.','Boil the eggs 9 minutes; serve everything hot.'],
    swaps:['Oats or ragi idli batter for more fibre','Paneer bhurji instead of eggs','Add drumstick and pumpkin to the sambar']}),
  RC({id:'pesarattu',name:'Pesarattu + Paneer + Curd',cat:'breakfast',cuisine:'South Indian',tags:['moong','dosa','paneer','high-protein'],
    upgrade:'Whole-moong dosa — no rice batter, all lentil protein.',
    ing:[['moongwhole',60,'g'],['brownrice',10,'g'],['onion',20,'g'],['paneer',30,'g'],['curd',100,'g'],['oil',5,'g']],
    serve:[[2,'','pesarattu'],[30,'g','paneer filling'],[100,'g','curd']],
    method:['Soak whole moong and a little rice overnight; grind with ginger, green chilli and cumin to a thick batter (no fermenting).','Spread thin on a hot tawa, scatter onion and grated paneer, drizzle oil.','Cook till crisp, fold and serve with curd and ginger chutney.'],
    swaps:['Upma filling for the guys','Tofu crumble instead of paneer','Add spinach to the batter']}),
  RC({id:'ragidosa',name:'Ragi Dosa + Egg + Sambar',cat:'breakfast',cuisine:'South Indian',tags:['ragi','millet','dosa','egg','calcium'],
    upgrade:'Ragi brings ~10× the calcium of rice; egg and sambar carry protein.',
    ing:[['ragi',40,'g'],['dosabatter',80,'g'],['toor',25,'g'],['mixveg',50,'g'],['egg',1,''],['oil',5,'g']],
    serve:[[2,'','ragi dosa'],[1,'','egg'],[150,'ml','sambar']],
    method:['Whisk ragi flour into the dosa batter with water and salt; rest 15 minutes.','Spread thin on a hot tawa, crack an egg over one dosa and spread it.','Serve with hot sambar.'],
    swaps:['Skip the egg and add paneer','Jowar flour instead of ragi','Coconut-peanut chutney on the side']}),
  RC({id:'daliyaupma',name:'Vegetable Daliya Upma + Egg + Curd',cat:'breakfast',cuisine:'South Indian',tags:['daliya','upma','egg','fibre'],
    upgrade:'Broken wheat instead of semolina doubles the fibre.',
    ing:[['daliya',50,'g'],['mixveg',60,'g'],['peanuts',15,'g'],['egg',1,''],['curd',100,'g'],['oil',5,'g']],
    serve:[[200,'g','daliya upma'],[1,'','egg'],[100,'g','curd']],
    method:['Dry-roast daliya till nutty.','Temper mustard, curry leaves, peanuts and chilli; add vegetables, then daliya and 2½× water.','Pressure-cook 2 whistles (or Instant Pot 5 min); serve with a boiled egg and curd.'],
    swaps:['Quinoa instead of daliya','Paneer cubes instead of egg','Add sprouts for more protein']}),
  RC({id:'uttapam',name:'Paneer Veg Uttapam + Sambar',cat:'breakfast',cuisine:'South Indian',tags:['uttapam','paneer','sambar'],
    upgrade:'Thick uttapam topped with paneer and veg instead of plain onion.',
    ing:[['dosabatter',150,'g'],['onion',30,'g'],['tomato',30,'g'],['capsicum',20,'g'],['paneer',40,'g'],['toor',20,'g'],['oil',5,'g']],
    serve:[[2,'','uttapam'],[40,'g','paneer'],[120,'ml','sambar']],
    method:['Pour thick rounds of batter on a hot tawa.','Press chopped onion, tomato, capsicum and crumbled paneer into the top.','Drizzle oil, cover and cook till set; flip briefly. Serve with sambar.'],
    swaps:['Egg on top instead of paneer','Oats-dosa batter','Add grated carrot']}),
  RC({id:'adai',name:'Adai (Mixed Dal Dosa) + Curd',cat:'breakfast',cuisine:'South Indian',tags:['dal','dosa','high-protein','fibre'],
    upgrade:'Three dals in one crisp dosa — protein and fibre without fermenting.',
    ing:[['chanadal',25,'g'],['toor',15,'g'],['moong',20,'g'],['brownrice',20,'g'],['onion',20,'g'],['curd',100,'g'],['oil',6,'g']],
    serve:[[2,'','adai'],[100,'g','curd']],
    method:['Soak the dals and rice 3 hours; grind coarse with red chilli, ginger and curry leaves.','Stir in chopped onion; spread on a hot tawa slightly thick.','Cook with a little oil till golden both sides; serve with curd.'],
    swaps:['Avial on the side','Add drumstick leaves (moringa)','Paneer filling for extra protein']}),
  RC({id:'appe',name:'Masala Oats Appe + Egg',cat:'breakfast',cuisine:'South Indian',tags:['appe','oats','egg','pan-baked'],
    upgrade:'Oats and egg folded into the batter; cooked in an appe pan with drops of oil.',
    ing:[['oats',30,'g'],['dosabatter',80,'g'],['egg',2,''],['onion',20,'g'],['carrot',20,'g'],['oil',4,'g']],
    serve:[[10,'','appe']],
    method:['Grind oats to a powder; mix into the batter with beaten eggs, onion, carrot, chilli and coriander.','Spoon into a lightly oiled appe (paniyaram) pan.','Cook covered 3 minutes, turn and cook 2 more. Serve with chutney.'],
    swaps:['Paneer instead of egg','Ragi flour instead of oats','Add spinach']}),
  RC({id:'ragiporridge',name:'Ragi Banana Protein Porridge',cat:'breakfast',cuisine:'South Indian',tags:['ragi','no-sugar','whey','calcium'],
    upgrade:'Ragi malt with whey and almond butter — banana does the sweetening.',
    ing:[['ragi',40,'g'],['milk',200,'ml'],['banana',0.5,''],['whey',15,'g'],['almondbutter',10,'g']],
    serve:[[300,'ml','porridge']],
    method:['Whisk ragi flour into cold milk and water; cook on low, stirring, 6–8 minutes until thick.','Take off the heat; whisk in whey (so it doesn’t clump), mashed banana and cardamom.','Top with almond butter.'],
    swaps:['Monkfruit or allulose if you want it sweeter','Soy milk to go dairy-free','Oats instead of ragi']}),
  // Gujarati
  RC({id:'thepla',name:'Methi Thepla + Curd + Egg',cat:'breakfast',cuisine:'Gujarati',tags:['thepla','methi','egg','packable'],
    upgrade:'Methi and besan in the dough; curd and an egg round out protein.',
    ing:[['atta',60,'g'],['besan',10,'g'],['methi',30,'g'],['curd',100,'g'],['oil',5,'g'],['egg',1,'']],
    serve:[[3,'','thepla'],[100,'g','curd'],[1,'','boiled egg']],
    method:['Knead atta, besan, chopped methi, a spoon of curd, turmeric, chilli and salt into a soft dough.','Roll thin and cook on a tawa with a few drops of oil.','Serve with curd and a boiled egg. Theplas keep 2 days — make a double batch.'],
    swaps:['Paneer bhurji instead of egg','Add grated lauki to the dough','Bajra flour for half the atta']}),
  RC({id:'khaman',name:'Besan Khaman + Mint Yogurt',cat:'breakfast',cuisine:'Gujarati',tags:['khaman','besan','steamed','high-protein'],
    upgrade:'Steamed besan is ~22% protein; skip the sugar syrup.',
    ing:[['besan',70,'g'],['curd',60,'g'],['oil',5,'g'],['greek',100,'g']],
    serve:[[6,'','khaman pieces'],[100,'g','mint Greek-yogurt dip']],
    method:['Whisk besan, curd, water, ginger-chilli paste and salt; rest 10 minutes. Stir in fruit salt (Eno) just before steaming.','Steam in a greased tin 15 minutes.','Temper mustard seeds, sesame and curry leaves in oil with a splash of water (no sugar); pour over. Serve with mint yogurt.'],
    swaps:['Moong dal khaman','Sweeten the tempering with allulose if wanted','Add grated paneer on top']}),
  RC({id:'handvo',name:'Baked Lauki Handvo + Curd',cat:'breakfast',cuisine:'Gujarati',tags:['handvo','lentil','baked','make-ahead'],
    upgrade:'Rice-dal cake baked in the oven with bottle gourd folded in.',
    ing:[['brownrice',25,'g'],['toor',15,'g'],['chanadal',15,'g'],['moong',10,'g'],['lauki',80,'g'],['curd',160,'g'],['oil',6,'g']],
    serve:[[1,'','thick slice handvo'],[100,'g','curd']],
    method:['Soak rice and dals 4 hours; grind coarse with a little curd and ferment 6–8 hours.','Fold in grated lauki, ginger-chilli, turmeric and a pinch of soda.','Pour into an oiled tin, top with a mustard-sesame tempering, bake at 190°C for 40 minutes. Serve with curd.'],
    swaps:['Mixed veg instead of lauki','Make it in a pan as mini handvo','Add spinach']}),
  RC({id:'muthiya',name:'Steamed Lauki-Methi Muthiya + Greek Yogurt',cat:'breakfast',cuisine:'Gujarati',tags:['muthiya','steamed','lauki','methi'],
    upgrade:'Steamed, not fried, and served with Greek yogurt for protein.',
    ing:[['atta',30,'g'],['besan',30,'g'],['lauki',80,'g'],['methi',20,'g'],['oil',5,'g'],['greek',150,'g']],
    serve:[[8,'','muthiya'],[150,'g','Greek yogurt']],
    method:['Mix grated lauki, methi, atta, besan, ginger-chilli, turmeric and salt into a soft dough (the lauki gives the water).','Shape into logs and steam 20 minutes; cool and slice.','Temper with mustard, sesame and curry leaves in a little oil; serve with Greek yogurt.'],
    swaps:['Spinach instead of methi','Jowar flour instead of atta','Pan-crisp the slices for the guys']}),
  RC({id:'dhebra',name:'Bajra Methi Dhebra + Greek Yogurt',cat:'breakfast',cuisine:'Gujarati',tags:['bajra','millet','methi','PCOD'],
    upgrade:'Pearl millet is low-GI and iron-rich.',
    ing:[['bajra',60,'g'],['methi',20,'g'],['curd',30,'g'],['oil',5,'g'],['greek',120,'g']],
    serve:[[3,'','dhebra'],[120,'g','Greek yogurt']],
    method:['Knead bajra flour, chopped methi, curd, ginger-chilli, sesame and salt into a dough with warm water.','Pat into small rounds and cook on a tawa with a little oil.','Serve warm with Greek yogurt.'],
    swaps:['Jowar instead of bajra','Add grated paneer to the dough','Pair with a boiled egg']}),
  RC({id:'usal',name:'Sprout Usal + Egg Toast',cat:'breakfast',cuisine:'Maharashtrian',tags:['sprouts','egg','toast'],
    upgrade:'Sprouts and matki beat potato for breakfast protein.',
    ing:[['sprouts',150,'g'],['matki',20,'g'],['onion',30,'g'],['tomato',30,'g'],['bread',2,''],['egg',1,''],['oil',5,'g']],
    serve:[[180,'g','sprout usal'],[2,'slice','toast'],[1,'','egg']],
    method:['Cook sprouts and matki till just soft.','Sauté mustard, onion, tomato, goda masala; add the sprouts and simmer.','Serve with whole-grain toast and a fried egg.'],
    swaps:['Paneer instead of egg','Pav instead of toast','Add coconut for Konkan-style usal']}),
  // Punjabi & North Indian
  RC({id:'paneerbhurji',name:'Paneer Bhurji + Roti',cat:'breakfast',cuisine:'Punjabi',tags:['paneer','bhurji','roti'],
    upgrade:'Crumbled paneer with peppers — 13g protein per 70g.',
    ing:[['paneer',70,'g'],['onion',30,'g'],['tomato',40,'g'],['capsicum',30,'g'],['atta',40,'g'],['oil',4,'g']],
    serve:[[150,'g','paneer bhurji'],[1.5,'','roti']],
    method:['Sauté cumin, onion, ginger and chilli; add tomato and capsicum.','Crumble in paneer with turmeric and garam masala; cook 3 minutes.','Serve with fresh roti.'],
    swaps:['Half tofu, half paneer for Dvija','Egg bhurji instead','Toast instead of roti']}),
  RC({id:'sattuparatha',name:'Sattu Paratha + Curd',cat:'breakfast',cuisine:'North Indian',tags:['sattu','paratha','high-protein'],
    upgrade:'Roasted gram flour stuffing — Bihar’s protein secret.',
    ing:[['atta',50,'g'],['sattu',40,'g'],['onion',20,'g'],['curd',120,'g'],['ghee',5,'g']],
    serve:[[2,'','sattu parathas'],[120,'g','curd']],
    method:['Mix sattu with chopped onion, chilli, coriander, lemon, ajwain and a spoon of mustard oil.','Stuff into atta dough and roll gently.','Cook on a tawa with a light smear of ghee; serve with curd.'],
    swaps:['Add paneer to the stuffing','Jowar-atta dough','Serve with a boiled egg']}),
  RC({id:'omelette',name:'Masala Omelette + Toast',cat:'breakfast',cuisine:'North Indian',tags:['egg','egg-white','high-protein','quick'],
    upgrade:'Whole eggs plus egg whites: 30g+ protein for under 400 kcal.',
    ing:[['egg',2,''],['eggwhite',100,'g'],['onion',20,'g'],['tomato',20,'g'],['capsicum',20,'g'],['bread',2,''],['oil',4,'g']],
    serve:[[1,'','masala omelette'],[2,'slice','toast']],
    method:['Whisk eggs and whites with onion, tomato, capsicum, chilli, turmeric and salt.','Cook in a lightly oiled pan, fold.','Serve with whole-grain toast.'],
    swaps:['Add spinach and feta','Roti instead of toast','Tofu scramble for an egg-free day']}),
  RC({id:'andabhurji',name:'Anda Bhurji + Roti',cat:'breakfast',cuisine:'North Indian',tags:['egg','bhurji','roti'],
    upgrade:'Three eggs scrambled with masala — 19g protein before the roti.',
    ing:[['egg',3,''],['onion',30,'g'],['tomato',40,'g'],['atta',40,'g'],['oil',4,'g']],
    serve:[[3,'','egg bhurji'],[1.5,'','roti']],
    method:['Sauté onion, chilli and tomato with pav bhaji masala.','Add beaten eggs; stir gently till just set.','Serve with roti.'],
    swaps:['Replace one egg with 50g egg whites for Dvija','Paneer bhurji instead','Pav instead of roti']}),
  RC({id:'besanchilla',name:'Besan Chilla with Paneer + Curd',cat:'breakfast',cuisine:'North Indian',tags:['besan','chilla','paneer','high-protein'],
    upgrade:'Chickpea-flour pancakes stuffed with paneer.',
    ing:[['besan',50,'g'],['paneer',40,'g'],['onion',20,'g'],['tomato',20,'g'],['curd',100,'g'],['oil',5,'g']],
    serve:[[2,'','besan chilla'],[40,'g','paneer'],[100,'g','curd']],
    method:['Whisk besan with water, onion, tomato, ajwain, chilli and salt to a pourable batter.','Spread thin on a lightly oiled tawa; scatter grated paneer, fold when set.','Serve with curd or green chutney.'],
    swaps:['Tofu instead of paneer','Add spinach to the batter','Moong chilla instead']}),
  RC({id:'masalaoats',name:'Masala Oats + Eggs',cat:'breakfast',cuisine:'North Indian',tags:['oats','egg','quick'],
    upgrade:'Savoury oats loaded with veg, eggs on the side.',
    ing:[['oats',50,'g'],['mixveg',60,'g'],['egg',2,''],['oil',3,'g']],
    serve:[[220,'g','masala oats'],[2,'','eggs']],
    method:['Sauté cumin, onion, chilli and vegetables in a little oil.','Add oats, turmeric, garam masala and 2× water; cook 4 minutes.','Serve with boiled or poached eggs.'],
    swaps:['Paneer cubes instead of egg','Add peas and corn','Daliya instead of oats']}),
  RC({id:'quinoaupma',name:'Quinoa Upma + Egg',cat:'breakfast',cuisine:'Fusion',tags:['quinoa','upma','egg','gluten-free'],
    upgrade:'Quinoa is a complete protein grain.',
    ing:[['quinoa',50,'g'],['mixveg',70,'g'],['peanuts',10,'g'],['egg',1,''],['oil',4,'g']],
    serve:[[220,'g','quinoa upma'],[1,'','egg']],
    method:['Rinse quinoa well.','Temper mustard, curry leaves, peanuts and chilli; add vegetables and quinoa with 2× water.','Cook covered 12 minutes (Instant Pot 1 min + natural release). Serve with an egg.'],
    swaps:['Paneer instead of egg','Add sprouts','Millet instead of quinoa']}),
  // Farali breakfast
  RC({id:'kuttuchilla',name:'Kuttu Paneer Chilla + Curd',cat:'breakfast',farali:true,cuisine:'Gujarati',tags:['farali','vrat','kuttu','paneer','thursday'],
    upgrade:'Buckwheat is a vrat-friendly grain with real protein.',
    ing:[['kuttu',50,'g'],['paneer',50,'g'],['potato',40,'g'],['curd',100,'g'],['ghee',4,'g']],
    serve:[[2,'','kuttu chilla'],[50,'g','paneer'],[100,'g','curd']],
    method:['Whisk kuttu flour with grated boiled potato, sendha namak, green chilli and water.','Spread on a tawa with a little ghee; scatter grated paneer and fold.','Serve with curd.'],
    swaps:['Rajgira flour instead','Sweet potato instead of potato','Add peanut powder']}),

  /* ======================= LUNCH & DINNER ======================= */
  // South Indian
  RC({id:'sambarrice',name:'Sambar Rice + Beans Poriyal',cat:'main',leftover:true,cuisine:'South Indian',tags:['sambar','dal','rice','packable'],
    upgrade:'Brown rice, lots of veg in the sambar, and a coconut-light poriyal.',
    ing:[['toor',40,'g'],['brownrice',50,'g'],['mixveg',80,'g'],['beans',60,'g'],['coconut',5,'g'],['oil',5,'g'],['curd',75,'g']],
    serve:[[250,'g','sambar rice'],[80,'g','poriyal'],[75,'g','curd']],
    method:['Pressure-cook toor dal; cook brown rice (Instant Pot pot-in-pot works).','Simmer vegetables with tamarind and sambar powder; add the dal and temper.','Stir-fry chopped beans with mustard, urad dal and a little coconut for poriyal. Pack tomorrow’s lunch.'],
    swaps:['Millet instead of rice','Drumstick in the sambar','Cabbage poriyal']}),
  RC({id:'bisibele',name:'Bisi Bele Bath',cat:'main',leftover:true,cuisine:'South Indian',tags:['dal','rice','one-pot','packable'],
    upgrade:'One-pot lentil-rice with double the vegetables, less ghee.',
    ing:[['toor',35,'g'],['brownrice',45,'g'],['mixveg',100,'g'],['peanuts',8,'g'],['ghee',4,'g'],['curd',75,'g']],
    serve:[[320,'g','bisi bele bath'],[75,'g','raita']],
    method:['Pressure-cook toor dal, brown rice and vegetables together with turmeric (Instant Pot 22 min).','Stir in tamarind and bisi bele bath powder; simmer to a porridge.','Temper peanuts and curry leaves in ghee; serve with raita.'],
    swaps:['Foxtail millet instead of rice','Add peas and carrots','Skip ghee for Dvija']}),
  RC({id:'lemonrice',name:'Lemon Rice + Kala Chana Sundal',cat:'main',leftover:true,cuisine:'South Indian',tags:['rice','chana','packable','lunchbox'],
    upgrade:'The classic lunchbox, with a chana sundal for protein.',
    ing:[['brownrice',55,'g'],['peanuts',15,'g'],['kalachana',40,'g'],['coconut',5,'g'],['oil',5,'g']],
    serve:[[180,'g','lemon rice'],[120,'g','chana sundal']],
    method:['Cook brown rice; soak and pressure-cook kala chana.','Temper mustard, chana dal, peanuts, curry leaves and turmeric; toss with rice and lemon juice.','Temper the chana with mustard and coconut for sundal. Both pack well.'],
    swaps:['Quinoa instead of rice','Add grated carrot','Chickpeas instead of kala chana']}),
  RC({id:'avial',name:'Avial + Moong Dal + Brown Rice',cat:'main',leftover:true,cuisine:'South Indian',tags:['avial','coconut','dal','veg'],
    upgrade:'Mixed-veg avial in a curd-coconut base, with dal for protein.',
    ing:[['mixveg',120,'g'],['beans',50,'g'],['carrot',40,'g'],['coconut',15,'g'],['curd',80,'g'],['oil',4,'g'],['brownrice',45,'g'],['moong',30,'g']],
    serve:[[200,'g','avial'],[120,'g','moong dal'],[120,'g','brown rice']],
    method:['Steam vegetables cut into batons until just tender.','Grind coconut, cumin and green chilli; stir into the veg with curd and curry leaves (don’t boil).','Cook moong dal and brown rice; finish avial with a spoon of coconut oil.'],
    swaps:['Millet instead of rice','More curd, less coconut for Dvija','Add drumstick']}),
  RC({id:'kootu',name:'Lauki Chana Dal Kootu + Brown Rice',cat:'main',leftover:true,cuisine:'South Indian',tags:['kootu','dal','lauki'],
    upgrade:'Chana dal and bottle gourd in a light coconut gravy.',
    ing:[['chanadal',45,'g'],['lauki',120,'g'],['coconut',8,'g'],['brownrice',45,'g'],['oil',4,'g'],['curd',75,'g']],
    serve:[[250,'g','kootu'],[120,'g','brown rice'],[75,'g','curd']],
    method:['Pressure-cook chana dal with diced lauki and turmeric.','Grind coconut, cumin and pepper; stir in and simmer.','Temper with mustard and curry leaves; serve with brown rice and curd.'],
    swaps:['Cabbage or ash gourd instead of lauki','Moong dal instead of chana dal','Millet instead of rice']}),
  RC({id:'curdrice',name:'Curd Rice + Moong Kosambari',cat:'main',cuisine:'South Indian',tags:['curd-rice','probiotic','cooling'],
    upgrade:'Probiotic curd rice with a raw moong salad for protein.',
    ing:[['brownrice',45,'g'],['curd',200,'g'],['moong',25,'g'],['cucumber',50,'g'],['carrot',30,'g'],['peanuts',5,'g'],['oil',3,'g']],
    serve:[[250,'g','curd rice'],[100,'g','kosambari']],
    method:['Cook brown rice soft; cool and mix with curd, ginger and salt.','Temper mustard, curry leaves and chilli; pour over.','Soak moong dal 2 hours; toss with cucumber, carrot, lemon and peanuts for kosambari.'],
    swaps:['Greek yogurt for more protein','Pomegranate on top','Millet instead of rice']}),
  RC({id:'chettinad',name:'Chettinad Chicken / Mushroom-Tofu + Brown Rice',cat:'main',leftover:true,cuisine:'South Indian',tags:['chettinad','chicken','tofu','spicy'],
    upgrade:'Pepper-forward Chettinad masala; one gravy, two proteins.',
    ing:[['onion',40,'g'],['tomato',50,'g'],['mushroom',60,'g'],['coconut',8,'g'],['brownrice',45,'g'],['oil',6,'g']],
    protein:{veg:['tofu',120,'g','tofu'],chicken:['chicken',110,'g','chicken']},
    serve:[[200,'g','chettinad curry'],[120,'g','brown rice']],
    method:['Dry-roast pepper, fennel, cumin, coriander, red chilli and coconut; grind to the Chettinad masala.','Cook onion, tomato and mushrooms with the masala to a thick gravy. Split it into two pots.','Simmer chicken in one pot (Akshar & Aum) 15 minutes, tofu in the other (Dvija) 5 minutes.','Serve with brown rice. Pack tomorrow’s lunch from each pot.'],
    swaps:['Paneer instead of tofu','Kerala parotta-style whole-wheat roti','Millet instead of rice']}),
  RC({id:'keralastew',name:'Kerala Stew with Chicken / Tofu',cat:'main',leftover:true,cuisine:'South Indian',tags:['stew','coconut','chicken','tofu','mild'],
    upgrade:'Light coconut milk instead of full-fat; vegetables do the bulk.',
    ing:[['mixveg',80,'g'],['potato',40,'g'],['coconutmilk',80,'ml'],['onion',30,'g'],['brownrice',35,'g'],['oil',4,'g']],
    protein:{veg:['tofu',120,'g','tofu'],chicken:['chicken',110,'g','chicken']},
    serve:[[250,'g','stew'],[100,'g','brown rice']],
    method:['Sauté whole spices, ginger, green chilli, curry leaves and onion in a little coconut oil.','Add vegetables, potato and water; simmer till tender, then stir in light coconut milk. Split into two pots.','Poach chicken in one pot (Akshar & Aum) till cooked through; warm tofu in the other (Dvija).','Serve with brown rice or appam.'],
    swaps:['Paneer instead of tofu','Appam made with oats-rice batter','Add green peas']}),
  // Gujarati
  RC({id:'daldhokli',name:'Dal Dhokli',cat:'main',leftover:true,cuisine:'Gujarati',tags:['dal','dhokli','one-pot','comfort'],
    upgrade:'Whole-wheat dumplings in toor dal — less jaggery, more dal.',
    ing:[['toor',40,'g'],['atta',50,'g'],['besan',5,'g'],['peanuts',8,'g'],['ghee',5,'g']],
    serve:[[350,'g','dal dhokli']],
    method:['Pressure-cook toor dal; whisk smooth and simmer with tamarind, kokum, peanuts and spices (skip the jaggery).','Knead atta with besan, ajwain, turmeric and chilli; roll thin and cut into diamonds.','Drop the dhokli into the simmering dal; cook 10–12 minutes. Finish with a ghee tempering.'],
    swaps:['Jowar-atta dhokli','Add drumstick or lauki','Skip ghee for Dvija']}),
  RC({id:'undhiyu',name:'Oven Undhiyu + Bajra Rotla',cat:'main',leftover:true,cuisine:'Gujarati',tags:['undhiyu','winter','bajra','baked'],
    upgrade:'Muthiya baked not fried, vegetables slow-cooked with a fraction of the oil.',
    ing:[['sweetpotato',50,'g'],['potato',30,'g'],['baingan',50,'g'],['beans',60,'g'],['peas',40,'g'],['methi',15,'g'],['besan',15,'g'],['oil',7,'g'],['bajra',45,'g'],['curd',100,'g']],
    serve:[[300,'g','undhiyu'],[1,'','bajra rotla'],[100,'g','curd']],
    method:['Mix methi, besan and spices into small muthiya; bake at 200°C for 15 minutes.','Layer vegetables with green masala (coconut, coriander, garlic, chilli) in a pot or Instant Pot; cook till tender.','Fold in the muthiya. Pat bajra rotla by hand and cook on a tawa. Serve with curd.'],
    swaps:['Surti papdi instead of green beans','Jowar rotla','Add lilva (pigeon peas)']}),
  RC({id:'ringanolo',name:'Ringan no Olo + Bajra Rotla + Chaas',cat:'main',leftover:true,cuisine:'Gujarati',tags:['baingan','bharta','bajra','PCOD'],
    upgrade:'Smoky roasted eggplant with millet rotla — low-GI and filling.',
    ing:[['baingan',200,'g'],['onion',40,'g'],['tomato',50,'g'],['peas',30,'g'],['oil',5,'g'],['bajra',60,'g'],['chaas',200,'ml']],
    serve:[[200,'g','ringan olo'],[1.5,'','bajra rotla'],[200,'ml','chaas']],
    method:['Roast eggplants over a flame or at 230°C till collapsed; peel and mash.','Sauté garlic, spring onion, tomato and peas; add the mash and spices.','Serve with bajra rotla and spiced chaas.'],
    swaps:['Jowar rotla','Add paneer cubes for protein','Roti instead of rotla']}),
  RC({id:'magrotla',name:'Gujarati Mag + Bajra Rotla',cat:'main',leftover:true,cuisine:'Gujarati',tags:['moong','bajra','high-protein','PCOD'],
    upgrade:'Whole moong curry with millet — high fibre, high protein.',
    ing:[['moongwhole',55,'g'],['onion',30,'g'],['tomato',40,'g'],['oil',5,'g'],['bajra',40,'g'],['chaas',150,'ml']],
    serve:[[250,'g','mag'],[1,'','bajra rotla'],[150,'ml','chaas']],
    method:['Soak whole moong 6 hours; pressure-cook till soft (Instant Pot 12 min).','Temper mustard, cumin, garlic, onion and tomato; add moong, spices and simmer.','Serve with bajra rotla and chaas.'],
    swaps:['Brown rice instead of rotla','Sprouted moong for faster cooking','Add spinach']}),
  RC({id:'dalbhaat',name:'Gujarati Dal-Bhaat + Bhindi',cat:'main',leftover:true,cuisine:'Gujarati',tags:['dal','rice','bhindi','thali'],
    upgrade:'Classic thali, brown rice, bhindi stir-fried not fried.',
    ing:[['toor',40,'g'],['brownrice',45,'g'],['bhindi',100,'g'],['oil',6,'g'],['curd',75,'g']],
    serve:[[200,'g','Gujarati dal'],[120,'g','brown rice'],[100,'g','bhindi'],[75,'g','curd']],
    method:['Pressure-cook toor dal; whisk and simmer with tomato, kokum, ginger and spices (skip the jaggery).','Cook brown rice.','Stir-fry sliced bhindi with mustard, ajwain and a little besan till crisp. Serve with curd.'],
    swaps:['Tindora or cabbage instead of bhindi','Millet instead of rice','Add a roti']}),
  // Punjabi
  RC({id:'daltadka',name:'Dal Tadka + Jeera Brown Rice',cat:'main',leftover:true,cuisine:'Punjabi',tags:['dal','tadka','rice','comfort'],
    upgrade:'Toor-moong dal with a garlic tadka, brown jeera rice and curd.',
    ing:[['toor',25,'g'],['moong',20,'g'],['brownrice',50,'g'],['tomato',40,'g'],['onion',30,'g'],['ghee',5,'g'],['cucumber',60,'g'],['curd',100,'g']],
    serve:[[220,'g','dal tadka'],[140,'g','jeera rice'],[100,'g','curd']],
    method:['Pressure-cook toor and moong dal with turmeric.','Cook brown rice with cumin and bay leaf.','Make a tadka of ghee, cumin, garlic, onion, tomato and Kashmiri chilli; pour over the dal. Serve with curd and salad.'],
    swaps:['Masoor instead of moong','Add spinach for dal palak','Millet jeera rice']}),
  RC({id:'kadhipakora',name:'Punjabi Kadhi with Baked Pakoras + Rice',cat:'main',leftover:true,cuisine:'Punjabi',tags:['kadhi','besan','curd','baked'],
    upgrade:'Pakoras baked in an appe pan or oven, not deep-fried.',
    ing:[['curd',150,'g'],['besan',35,'g'],['onion',30,'g'],['spinach',30,'g'],['oil',5,'g'],['brownrice',45,'g']],
    serve:[[250,'ml','kadhi'],[4,'','baked pakoras'],[120,'g','brown rice']],
    method:['Whisk sour curd with besan, turmeric and water; simmer 25 minutes, stirring.','Mix besan with onion, spinach and spices; bake as small pakoras at 200°C (or in an appe pan) till crisp.','Temper fenugreek, cumin and red chilli; add pakoras just before serving with brown rice.'],
    swaps:['Low-fat curd for Dvija','Skip pakoras, add more spinach','Millet instead of rice']}),
  RC({id:'sarson',name:'Sarson ka Saag + Makki Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['saag','greens','makki','winter'],
    upgrade:'Greens-heavy saag with paneer cubes instead of a dollop of butter.',
    ing:[['sarson',150,'g'],['spinach',80,'g'],['onion',30,'g'],['ghee',5,'g'],['makki',60,'g'],['paneer',40,'g']],
    serve:[[250,'g','saag with paneer'],[2,'','makki roti']],
    method:['Pressure-cook mustard greens and spinach with ginger, garlic and chilli; blend coarse with a spoon of makki atta.','Temper onion in ghee, add the saag and simmer; fold in paneer cubes.','Make makki rotis on the tawa (pat between sheets). Serve with onion and lemon.'],
    swaps:['Tofu instead of paneer','Whole-wheat roti instead of makki','Add bathua or methi']}),
  RC({id:'aloogobi',name:'Aloo Gobi + Moong Dal + Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['aloo-gobi','dal','roti'],
    upgrade:'More gobi than aloo, dry-roasted, with a protein dal alongside.',
    ing:[['potato',60,'g'],['cauliflower',120,'g'],['moong',30,'g'],['atta',50,'g'],['oil',6,'g'],['tomato',30,'g']],
    serve:[[180,'g','aloo gobi'],[150,'g','moong dal'],[2,'','roti']],
    method:['Toss cauliflower and potato with turmeric, cumin and a little oil; roast at 220°C for 25 minutes.','Cook moong dal with tomato and a cumin tadka.','Toss the roasted veg with dry mango and garam masala; serve with roti.'],
    swaps:['All cauliflower for Dvija','Add peas','Masoor instead of moong']}),
  RC({id:'matarmushroom',name:'Matar Mushroom + Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['mushroom','peas','roti','light'],
    upgrade:'Greek yogurt makes the gravy creamy without cream.',
    ing:[['mushroom',120,'g'],['peas',70,'g'],['onion',30,'g'],['tomato',50,'g'],['atta',60,'g'],['oil',5,'g'],['greek',50,'g']],
    serve:[[220,'g','matar mushroom'],[2,'','roti']],
    method:['Cook onion, ginger-garlic and tomato into a masala.','Add mushrooms and peas; simmer 8 minutes.','Off the heat, stir in Greek yogurt and kasuri methi. Serve with roti.'],
    swaps:['Add paneer cubes','Brown rice instead of roti','Corn instead of peas']}),
  RC({id:'butterchicken',name:'Light Butter Chicken / Paneer Makhani',cat:'main',leftover:true,cuisine:'Punjabi',tags:['makhani','chicken','paneer','creamy'],
    upgrade:'Cashew-milk makhani base with a teaspoon of butter, not cream.',
    ing:[['tomato',120,'g'],['onion',30,'g'],['cashew',8,'g'],['milk',50,'ml'],['butter',4,'g'],['brownrice',45,'g']],
    protein:{veg:['paneer',70,'g','paneer'],chicken:['chicken',120,'g','chicken']},
    serve:[[220,'g','makhani'],[120,'g','brown rice']],
    method:['Marinate chicken in yogurt, ginger-garlic and tandoori masala; roast at 230°C for 15 minutes (or pan-sear).','Simmer tomato, onion and soaked cashews; blend smooth. Return to the pan with butter, kasuri methi and milk. Split into two pots.','Add chicken to one pot (Akshar & Aum), paneer to the other (Dvija); simmer 5 minutes.','Serve with brown rice or roti.'],
    swaps:['Tofu instead of paneer for Dvija','Roti instead of rice','Skip the butter']}),
  RC({id:'tikkamasala',name:'Chicken / Paneer Tikka Masala + Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['tikka','chicken','paneer','oven'],
    upgrade:'Tikka roasted in the oven; yogurt marinade instead of cream.',
    ing:[['onion',40,'g'],['tomato',80,'g'],['greek',50,'g'],['capsicum',40,'g'],['oil',5,'g'],['atta',50,'g']],
    protein:{veg:['paneer',70,'g','paneer'],chicken:['chicken',120,'g','chicken']},
    serve:[[220,'g','tikka masala'],[2,'','roti']],
    method:['Marinate chicken and paneer separately in Greek yogurt, lemon, ginger-garlic and tikka masala.','Roast both on separate trays with capsicum and onion at 230°C (chicken 18 min, paneer 10 min).','Make an onion-tomato masala; split it and stir the chicken into one pot, paneer into the other. Serve with roti.'],
    swaps:['Tofu tikka for Dvija','Brown rice instead of roti','Add mushrooms to the trays']}),
  RC({id:'saagchicken',name:'Saag Chicken / Saag Tofu + Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['saag','spinach','chicken','tofu','iron'],
    upgrade:'Spinach-methi base for iron; lean protein for both versions.',
    ing:[['spinach',150,'g'],['methi',30,'g'],['onion',30,'g'],['tomato',40,'g'],['oil',5,'g'],['atta',50,'g']],
    protein:{veg:['tofu',130,'g','tofu'],chicken:['chicken',120,'g','chicken']},
    serve:[[250,'g','saag'],[2,'','roti']],
    method:['Blanch spinach and methi; blend smooth.','Cook onion, ginger-garlic, tomato and garam masala; add the greens. Split into two pots.','Simmer chicken in one pot 15 minutes (Akshar & Aum); add pan-seared tofu to the other (Dvija).','Serve with roti.'],
    swaps:['Paneer instead of tofu','Brown rice instead of roti','Add sarson for a sharper saag']}),
  // North Indian
  RC({id:'laukidal',name:'Lauki Chana Dal + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['dal','lauki','light'],
    upgrade:'Bottle gourd bulks the dal for very few calories.',
    ing:[['chanadal',45,'g'],['lauki',150,'g'],['tomato',40,'g'],['ghee',4,'g'],['atta',50,'g']],
    serve:[[280,'g','lauki chana dal'],[2,'','roti']],
    method:['Soak chana dal 1 hour; pressure-cook with diced lauki, turmeric and salt.','Temper cumin, garlic, tomato and garam masala in ghee; stir in.','Serve with roti.'],
    swaps:['Moong dal instead of chana dal','Brown rice instead of roti','Add spinach']}),
  RC({id:'soyacurry',name:'Soya Chunk Matar Curry + Brown Rice',cat:'main',leftover:true,cuisine:'North Indian',tags:['soy','high-protein','PCOD','budget'],
    upgrade:'Soya chunks are ~50% protein — the cheapest protein in the pantry.',
    ing:[['soy',35,'g'],['onion',40,'g'],['tomato',60,'g'],['peas',40,'g'],['oil',5,'g'],['brownrice',45,'g']],
    serve:[[220,'g','soya matar'],[120,'g','brown rice']],
    method:['Soak soya chunks in hot salted water 10 minutes; squeeze dry.','Cook onion, ginger-garlic and tomato with garam masala; add peas and soya and simmer 10 minutes.','Serve with brown rice.'],
    swaps:['Roti instead of rice','Add potato for the guys','Paneer and soya mix']}),
  RC({id:'bharta',name:'Baingan Bharta + Masoor Dal + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['bharta','baingan','dal','smoky'],
    upgrade:'Fire-roasted eggplant with a red-lentil dal for protein.',
    ing:[['baingan',200,'g'],['onion',30,'g'],['tomato',50,'g'],['peas',30,'g'],['oil',5,'g'],['masoor',30,'g'],['atta',40,'g']],
    serve:[[180,'g','bharta'],[150,'g','masoor dal'],[1.5,'','roti']],
    method:['Roast eggplants over a flame or at 230°C; peel and mash.','Cook onion, garlic, tomato and peas; add the mash and spices.','Pressure-cook masoor dal with a cumin tadka. Serve with roti.'],
    swaps:['Bajra roti','Moong dal instead of masoor','Add paneer to the bharta']}),
  RC({id:'masoorveg',name:'Masoor Dal + Mix Veg + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['dal','mix-veg','roti','iron'],
    upgrade:'Red lentils cook in 15 minutes and are iron-rich.',
    ing:[['masoor',40,'g'],['mixveg',120,'g'],['oil',6,'g'],['atta',50,'g'],['curd',75,'g']],
    serve:[[200,'g','masoor dal'],[150,'g','mix veg'],[2,'','roti'],[75,'g','curd']],
    method:['Pressure-cook masoor dal with turmeric; finish with a garlic tadka.','Stir-fry mixed vegetables with cumin, coriander and dry mango.','Serve with roti and curd.'],
    swaps:['Brown rice instead of roti','Add paneer to the veg','Moong instead of masoor']}),
  RC({id:'lobia',name:'Lobia Curry + Brown Rice',cat:'main',leftover:true,cuisine:'North Indian',tags:['lobia','beans','fibre','packable'],
    upgrade:'Black-eyed peas — high fibre, high iron.',
    ing:[['lobia',55,'g'],['onion',30,'g'],['tomato',50,'g'],['oil',5,'g'],['brownrice',45,'g']],
    serve:[[230,'g','lobia curry'],[120,'g','brown rice']],
    method:['Soak lobia 4 hours; pressure-cook till soft (Instant Pot 10 min).','Cook onion, ginger-garlic and tomato with chole masala; add lobia and simmer.','Serve with brown rice.'],
    swaps:['Roti instead of rice','Add spinach','Rajma instead of lobia']}),
  RC({id:'kalachanacurry',name:'Kala Chana Curry + Jeera Rice',cat:'main',leftover:true,cuisine:'North Indian',tags:['chana','fibre','packable'],
    upgrade:'Black chickpeas have more fibre and iron than kabuli chana.',
    ing:[['kalachana',55,'g'],['onion',30,'g'],['tomato',50,'g'],['oil',5,'g'],['brownrice',45,'g'],['curd',75,'g']],
    serve:[[230,'g','kala chana'],[120,'g','jeera rice'],[75,'g','curd']],
    method:['Soak kala chana overnight; pressure-cook till soft (Instant Pot 30 min).','Cook onion, ginger-garlic and tomato with garam masala; add chana and simmer to a thick gravy.','Serve with brown jeera rice and curd.'],
    swaps:['Roti instead of rice','Dry chana masala for lunchboxes','Add spinach']}),
  RC({id:'kadai',name:'Kadai Chicken / Kadai Paneer + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['kadai','chicken','paneer','peppers'],
    upgrade:'Bell-pepper heavy kadai masala; lean chicken or paneer.',
    ing:[['capsicum',80,'g'],['onion',40,'g'],['tomato',70,'g'],['oil',5,'g'],['atta',50,'g']],
    protein:{veg:['paneer',75,'g','paneer'],chicken:['chicken',130,'g','chicken']},
    serve:[[230,'g','kadai'],[2,'','roti']],
    method:['Dry-roast and crush coriander seeds and red chillies for kadai masala.','Cook onion, tomato and the masala; add capsicum chunks. Split into two pans.','Cook chicken in one pan 12–15 minutes (Akshar & Aum); add paneer to the other for 3 minutes (Dvija).','Serve with roti.'],
    swaps:['Tofu instead of paneer for Dvija','Brown rice instead of roti','Add mushrooms']}),
  RC({id:'biryani',name:'Chicken / Paneer Brown-Rice Biryani',cat:'main',leftover:true,cuisine:'North Indian',tags:['biryani','chicken','paneer','one-pot'],
    upgrade:'Brown basmati, yogurt marinade and loads of veg; two pots, one masala.',
    ing:[['brownrice',55,'g'],['onion',50,'g'],['greek',50,'g'],['mixveg',50,'g'],['oil',5,'g']],
    protein:{veg:['paneer',60,'g','paneer'],chicken:['chicken',110,'g','chicken']},
    serve:[[320,'g','biryani'],[75,'g','raita']],
    method:['Marinate chicken and paneer separately in Greek yogurt, ginger-garlic and biryani masala.','Caramelise the onions in a little oil (not fried); add vegetables and soaked brown rice.','Make two Instant Pot or pressure-cooker batches: chicken with rice (Akshar & Aum), paneer with rice (Dvija); cook 22 minutes.','Serve with raita.'],
    swaps:['Soya chunks instead of paneer','Quinoa biryani for Dvija','Add mint and saffron']}),
  RC({id:'keema',name:'Chicken Keema / Soya Keema Matar + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['keema','chicken','soy','high-protein'],
    upgrade:'Lean chicken mince for the guys, soya keema for Dvija — both 25g+ protein.',
    ing:[['onion',40,'g'],['tomato',60,'g'],['peas',60,'g'],['oil',5,'g'],['atta',50,'g']],
    protein:{veg:['soy',40,'g','soya keema'],chicken:['chicken',120,'g','chicken keema']},
    serve:[[230,'g','keema matar'],[2,'','roti']],
    method:['Soak soya granules in hot water; squeeze dry. Mince the chicken breast (or buy lean ground).','Cook onion, ginger-garlic, tomato and keema masala; add peas. Split into two pans.','Cook chicken mince in one pan 10 minutes (Akshar & Aum); soya keema in the other 5 minutes (Dvija).','Serve with roti or pav.'],
    swaps:['Brown rice instead of roti','Add spinach','Paneer bhurji instead of soya']}),
  RC({id:'eggcurry',name:'Egg Curry + Brown Rice',cat:'main',leftover:true,cuisine:'North Indian',tags:['egg','curry','rice'],
    upgrade:'Three eggs in an onion-tomato gravy — simple, cheap protein.',
    ing:[['egg',3,''],['onion',40,'g'],['tomato',70,'g'],['oil',5,'g'],['brownrice',45,'g']],
    serve:[[3,'','eggs in gravy'],[120,'g','brown rice']],
    method:['Hard-boil the eggs; peel and score.','Cook onion, ginger-garlic and tomato with garam masala to a thick gravy.','Simmer the eggs in the gravy 5 minutes; serve with brown rice.'],
    swaps:['Roti instead of rice','Add spinach','Paneer instead of eggs']}),
  RC({id:'dalpalak',name:'Dal Palak + Brown Rice + Curd',cat:'main',leftover:true,cuisine:'North Indian',tags:['dal','spinach','iron','PCOD'],
    upgrade:'Spinach folded into dal for iron and folate.',
    ing:[['toor',30,'g'],['moong',15,'g'],['spinach',120,'g'],['tomato',40,'g'],['ghee',5,'g'],['brownrice',45,'g'],['curd',75,'g']],
    serve:[[250,'g','dal palak'],[120,'g','brown rice'],[75,'g','curd']],
    method:['Pressure-cook toor and moong dal.','Wilt chopped spinach into a garlic-tomato tadka; add the dal and simmer.','Serve with brown rice and curd.'],
    swaps:['Methi instead of spinach','Roti instead of rice','Masoor dal instead']}),
  // Fusion
  RC({id:'quinoabowl',name:'Paneer Tikka Quinoa Bowl',cat:'main',leftover:true,cuisine:'Fusion',tags:['quinoa','paneer','bowl','packable'],
    upgrade:'Quinoa base with oven paneer tikka and a yogurt dressing.',
    ing:[['quinoa',50,'g'],['paneer',60,'g'],['capsicum',50,'g'],['onion',30,'g'],['greek',50,'g'],['cucumber',50,'g'],['oil',4,'g']],
    serve:[[150,'g','quinoa'],[60,'g','paneer tikka'],[80,'g','roast veg']],
    method:['Cook quinoa.','Marinate paneer, capsicum and onion in yogurt and tikka masala; roast at 230°C for 12 minutes.','Assemble bowls with cucumber and a mint-yogurt dressing. Pack dressing separately.'],
    swaps:['Tofu tikka for Dvija','Brown rice instead of quinoa','Add chickpeas']}),
  RC({id:'hakka',name:'Tofu Hakka Noodles',cat:'main',leftover:true,cuisine:'Indo-Chinese',tags:['noodles','tofu','indo-chinese'],
    upgrade:'Whole-wheat noodles, lots of tofu and veg, light on oil.',
    ing:[['noodles',55,'g'],['tofu',100,'g'],['cabbage',60,'g'],['capsicum',40,'g'],['carrot',30,'g'],['oil',6,'g']],
    serve:[[300,'g','hakka noodles']],
    method:['Boil noodles al dente; rinse cold and toss with a few drops of oil.','Pan-sear pressed tofu cubes till golden.','Stir-fry garlic, cabbage, capsicum and carrot on high heat; add noodles, tofu, soy sauce, vinegar and pepper.'],
    swaps:['Egg hakka noodles','Paneer instead of tofu','Millet noodles']}),
  RC({id:'kathiroll',name:'Paneer Kathi Roll',cat:'main',cuisine:'Fusion',tags:['roll','paneer','wrap'],
    upgrade:'Whole-wheat wrap, grilled paneer and a yogurt-mint sauce.',
    ing:[['tortilla',1.5,''],['paneer',60,'g'],['onion',30,'g'],['capsicum',30,'g'],['greek',30,'g'],['oil',3,'g']],
    serve:[[1.5,'','kathi roll']],
    method:['Marinate paneer strips in tikka masala; grill on a tawa with onion and capsicum.','Warm the wrap; spread mint-yogurt sauce.','Fill, roll tight and halve.'],
    swaps:['Egg roll (egg cooked onto the wrap)','Tofu instead of paneer','Add pickled onions']}),
  // Farali mains
  RC({id:'shakarkand',name:'Shakarkand Paneer Chaat Bowl',cat:'main',farali:true,cuisine:'Gujarati',tags:['farali','vrat','sweet-potato','paneer','thursday'],
    upgrade:'Roasted sweet potato with paneer and Greek yogurt — the highest-protein farali meal.',
    ing:[['sweetpotato',200,'g'],['paneer',60,'g'],['greek',100,'g'],['peanuts',10,'g'],['lemon',10,'ml']],
    serve:[[200,'g','roast sweet potato'],[60,'g','paneer'],[100,'g','yogurt']],
    method:['Cube sweet potato and paneer; roast at 220°C for 25 minutes with sendha namak and cumin.','Toss with lemon, green chilli and roasted peanuts.','Top with whisked Greek yogurt.'],
    swaps:['Potato instead of sweet potato','Add pomegranate','Makhana for crunch']}),
  RC({id:'singhara',name:'Singhara Roti + Paneer Aloo + Curd',cat:'main',farali:true,cuisine:'Gujarati',tags:['farali','vrat','singhara','thursday'],
    upgrade:'Water-chestnut flour rotis with a paneer-potato sabzi.',
    ing:[['singhara',50,'g'],['potato',70,'g'],['paneer',40,'g'],['curd',150,'g'],['ghee',5,'g']],
    serve:[[2,'','singhara roti'],[150,'g','paneer aloo'],[150,'g','curd']],
    method:['Knead singhara flour with mashed potato, sendha namak and warm water; roll between sheets and cook on a tawa.','Sauté cumin and green chilli in ghee; add boiled potato and paneer cubes.','Serve with curd.'],
    swaps:['Kuttu flour instead','Sweet potato instead of potato','Add peanut curd']}),
  RC({id:'faraliBhurji',name:'Farali Paneer Bhurji + Rajgira Roti',cat:'main',farali:true,cuisine:'Gujarati',tags:['farali','vrat','paneer','rajgira','thursday'],
    upgrade:'Paneer bhurji made vrat-style, with amaranth rotis.',
    ing:[['paneer',70,'g'],['potato',40,'g'],['peanuts',8,'g'],['rajgira',45,'g'],['ghee',4,'g']],
    serve:[[150,'g','paneer bhurji'],[2,'','rajgira roti']],
    method:['Sauté cumin, green chilli and diced boiled potato in ghee.','Crumble in paneer with sendha namak and black pepper; add crushed peanuts.','Serve with rajgira rotis.'],
    swaps:['Kuttu roti','Add makhana','Sweet potato instead of potato']}),
);
