/* Weekly snack box — one batch made on Sunday, a serving a day through the week.
   No added sugar: sweetened with banana, a little honey, or monkfruit. One serving ≈ 130–180 kcal. */
RECIPES.push(
  RC({id:'makhana',name:'Masala Roasted Makhana + Peanuts',cat:'snack',cuisine:'Gujarati',tags:['makhana','savoury','crunchy','keeps-2-weeks'],
    upgrade:'Fox nuts are light, crunchy and high in fibre; peanuts add protein.',
    keeps:'2 weeks in an airtight jar',
    ing:[['makhana',25,'g'],['peanuts',8,'g'],['ghee',2,'g']],
    serve:[[1,'','small bowl (25 g makhana + peanuts)']],
    method:['Dry-roast makhana on low heat 8–10 minutes until it snaps when pressed.','Warm ghee with turmeric, chaat masala, black pepper and kala namak; toss the makhana and peanuts through.','Cool completely and store airtight. Portion one bowl a day.'],
    swaps:['Peri-peri or pudina masala','Add roasted chana for more protein','Air-tight jars keep it crisp']}),
  RC({id:'seedcookie',name:'All-Seed Oat Cookies',cat:'snack',cuisine:'Make-ahead',tags:['cookie','seeds','no-sugar','sweet'],
    upgrade:'Pumpkin, sunflower, flax and chia seeds with almond butter — sweetened with monkfruit and a touch of honey.',
    keeps:'1 week airtight',
    ing:[['oats',12,'g'],['almondbutter',7,'g'],['pumpkinseed',4,'g'],['sunflower',4,'g'],['flax',3,'g'],['chia',2,'g'],['honey',3,'g'],['egg',0.12,''],['monkfruit',3,'g']],
    serve:[[2,'','cookies']],
    method:['Mix oats, ground flax, chia, seeds, monkfruit, cinnamon and a pinch of salt.','Whisk almond butter, honey and egg; stir into the dry mix and rest 10 minutes.','Scoop small cookies onto a lined tray, flatten, and bake at 175°C for 12–14 minutes. Cool on the tray.'],
    swaps:['Peanut butter instead of almond butter','Add 85% dark chocolate chips','Egg-free: use a flax egg']}),
  RC({id:'brownie',name:'Black-Bean Protein Brownies',cat:'snack',cuisine:'Make-ahead',tags:['brownie','chocolate','no-sugar','sweet','high-protein'],
    upgrade:'Black beans and whey replace flour and sugar; 85% chocolate keeps it rich.',
    keeps:'1 week refrigerated',
    ing:[['blackbean',12,'g'],['cocoa',5,'g'],['whey',8,'g'],['egg',0.15,''],['almondbutter',5,'g'],['darkchoc',5,'g'],['monkfruit',6,'g']],
    serve:[[1,'','brownie square']],
    method:['Cook soaked black beans until very soft (Instant Pot 25 min); drain well and cool.','Blend beans, eggs, almond butter, cocoa, whey, monkfruit, vanilla and baking powder until smooth.','Fold in chopped dark chocolate; bake in a lined tin at 175°C for 20–22 minutes. Cool fully, cut into squares.'],
    swaps:['Add walnuts','Greek-yogurt frosting','Chickpeas instead of black beans']}),
  RC({id:'tiramisu',name:'Protein Tiramisu Cups',cat:'snack',cuisine:'Make-ahead',tags:['tiramisu','coffee','no-sugar','sweet','high-protein'],
    upgrade:'Greek yogurt and whey in place of mascarpone and sugar — 20g protein a cup.',
    keeps:'4–5 days refrigerated (make a second batch mid-week)',
    ing:[['greek',120,'g'],['whey',8,'g'],['oats',10,'g'],['cocoa',3,'g'],['darkchoc',3,'g'],['monkfruit',4,'g']],
    serve:[[1,'','tiramisu cup']],
    method:['Whisk Greek yogurt, whey, monkfruit and vanilla until smooth.','Toss oats in a little strong coffee.','Layer coffee-oats and yogurt in small jars; dust with cocoa and grated dark chocolate. Chill overnight.'],
    swaps:['Decaf coffee','Crumbled seed cookie instead of oats','Add berries between layers']}),
  RC({id:'bananaloaf',name:'Banana-Walnut Oat Loaf',cat:'snack',cuisine:'Make-ahead',tags:['cake','banana','walnut','no-sugar','sweet'],
    upgrade:'Oat flour, ripe banana and Greek yogurt — no sugar, no maida.',
    keeps:'5 days refrigerated, or freeze slices',
    ing:[['oats',20,'g'],['banana',0.25,''],['egg',0.2,''],['greek',20,'g'],['walnut',4,'g'],['honey',3,'g']],
    serve:[[1,'','slice']],
    method:['Blend oats to flour. Mash very ripe bananas.','Whisk bananas, eggs, Greek yogurt, honey and cinnamon; fold in oat flour, baking powder and chopped walnuts.','Bake in a lined loaf tin at 175°C for 45 minutes. Cool fully and slice into 8–10 pieces.'],
    swaps:['Ragi flour for half the oats','Add dark chocolate chips','Carrot instead of half the banana']}),
  RC({id:'proteinballs',name:'Chocolate Peanut Protein Balls',cat:'snack',cuisine:'Make-ahead',tags:['no-bake','chocolate','peanut','no-sugar','sweet','high-protein'],
    upgrade:'No-bake bites with whey and chia — a sweet fix with 11g protein.',
    keeps:'2 weeks refrigerated',
    ing:[['oats',10,'g'],['pb',8,'g'],['whey',8,'g'],['cocoa',3,'g'],['honey',4,'g'],['chia',2,'g']],
    serve:[[2,'','balls']],
    method:['Stir oats, whey, cocoa and chia together.','Warm peanut butter and honey slightly; mix in until it holds together (add a splash of milk if dry).','Roll into small balls and chill. Keep two a day.'],
    swaps:['Almond butter instead of PB','Roll in desiccated coconut','Add chopped dates for the guys']}),
  RC({id:'trailmix',name:'Roasted Chana-Seed Trail Mix',cat:'snack',cuisine:'Make-ahead',tags:['chana','seeds','savoury','keeps-2-weeks'],
    upgrade:'Roasted chana is 22% protein; seeds add healthy fats and magnesium.',
    keeps:'2 weeks airtight',
    ing:[['roastedchana',25,'g'],['pumpkinseed',5,'g'],['makhana',5,'g'],['darkchoc',3,'g']],
    serve:[[1,'','handful (~40 g)']],
    method:['Toast roasted chana, pumpkin seeds and makhana with a pinch of chaat masala.','Cool; add chopped 85% dark chocolate.','Pre-portion into 7 small bags or jars.'],
    swaps:['Sunflower seeds instead of pumpkin','Skip chocolate for a savoury mix','Add a few walnuts']}),
  RC({id:'khakhra',name:'Baked Methi Khakhra',cat:'snack',cuisine:'Gujarati',tags:['khakhra','methi','crispy','savoury'],
    upgrade:'Whole-wheat and besan crisps roasted on the tawa — Gujarati crackers without the frying.',
    keeps:'2 weeks airtight',
    ing:[['atta',25,'g'],['besan',5,'g'],['methi',8,'g'],['oil',2,'g']],
    serve:[[2,'','khakhra']],
    method:['Knead atta, besan, chopped methi, ajwain, chilli and salt with a little oil into a firm dough.','Roll paper-thin; half-cook on the tawa.','Press with a cloth on low heat until crisp and spotty all over. Cool and stack.'],
    swaps:['Masala or jeera khakhra','Bajra khakhra','Serve with a spoon of Greek-yogurt dip']}),
);
