/* Recipe library. Every recipe is written for ONE standard serving:
   ing   = raw ingredients for one serving  [foodKey, qty, unit]  (unit '' = count, 'g', 'ml')
   serve = what one serving looks like on the plate  [qty, unit, label]
   Each person eats a multiple of a serving (worked out from their calorie budget), and the
   family batch is the sum of everyone's servings — including tomorrow's leftover lunch. */
const RC = o => Object.assign({tags:[],swaps:[],method:[],leftover:false,farali:false,cuisine:''},o);

const RECIPES = [
  /* ---------- fixed daily items ---------- */
  RC({id:'mdrink',name:'Morning Seed Water',cat:'drink',fixed:true,cuisine:'Daily',
    upgrade:'Creatine + collagen with soaked seeds for fibre and omega-3s.',
    ing:[['creatine',5,'g'],['collagen',5,'g'],['chia',5,'g'],['flax',5,'g'],['basil',5,'g'],['honey',5,'g'],['lemon',5,'ml']],
    serve:[[300,'ml','warm water with seeds']],
    method:['Soak chia and basil seeds in a cup of water for 10 minutes.','Stir in ground flax, creatine, collagen, honey and lemon.','Top up with warm water and drink first thing.']}),
  RC({id:'shake_lite',name:'Lean Whey-Yogurt Shake',cat:'shake',fixed:true,cuisine:'Daily',
    upgrade:'35g protein for ~230 kcal — protects muscle in a deficit.',
    ing:[['whey',30,'g'],['greek',100,'g'],['banana',0.5,'']],serve:[[1,'scoop','whey'],[100,'g','Greek yogurt'],[0.5,'','banana'],[200,'ml','water']],
    method:['Blend whey, Greek yogurt, banana and cold water with ice.']}),
  RC({id:'shake_gain',name:'PB-Banana Gainer Shake',cat:'shake',fixed:true,cuisine:'Daily',
    upgrade:'Whey + milk + PB: the easiest 440 kcal of the day.',
    ing:[['whey',30,'g'],['milk',250,'ml'],['banana',1,''],['pb',16,'g']],
    serve:[[1,'scoop','whey'],[250,'ml','milk'],[1,'','banana'],[1,'tbsp','PB']],
    method:['Blend everything until smooth.']}),

  /* ---------- breakfasts ---------- */
  RC({id:'chilla',name:'Moong Chilla + Egg + Curd',cat:'breakfast',cuisine:'Gujarati',tags:['moong','egg','high-protein'],
    upgrade:'Three protein sources stacked — moong dal, egg, curd.',
    ing:[['moong',50,'g'],['egg',1,''],['curd',75,'g'],['onion',15,'g'],['oil',5,'g']],
    serve:[[2,'','chilla'],[1,'','egg'],[75,'g','curd']],
    method:['Soak the moong dal 3 hours (or overnight); blend with chilli, ginger and water to a pourable batter.','Season with salt and chopped onion.','Ladle thin rounds onto a hot non-stick tawa with a few drops of oil; cook both sides till golden.','Fry or boil the eggs alongside; serve with curd.'],
    swaps:['Tofu bhurji instead of egg','Grate paneer into the batter for extra protein','Besan chilla if out of moong']}),
  RC({id:'eggsando',name:'Feta-Veggie Egg Sandwich',cat:'breakfast',cuisine:'Fusion',tags:['egg','feta','sandwich'],
    upgrade:'Whole eggs + feta on whole-grain bread.',
    ing:[['bread',2,''],['egg',2,''],['feta',20,'g'],['spinach',20,'g'],['tomato',40,'g'],['onion',15,'g'],['oil',3,'g']],
    serve:[[2,'slice','whole-grain bread'],[2,'','eggs'],[20,'g','feta']],
    method:['Scramble the eggs soft with pepper and wilted spinach.','Warm the bread; layer eggs, crumbled feta, tomato and onion.','Press briefly on the tawa, halve and serve.'],
    swaps:['Paneer bhurji instead of egg','Multigrain wrap instead of bread','Avocado instead of feta (lower sodium)']}),
  RC({id:'poha',name:'Poha with Peanuts + Eggs',cat:'breakfast',cuisine:'Gujarati',tags:['poha','peanut','egg'],
    upgrade:'Peanuts, peas and 2 eggs turn a carb breakfast protein-real.',
    ing:[['poha',45,'g'],['egg',2,''],['peanuts',15,'g'],['onion',30,'g'],['peas',30,'g'],['oil',5,'g']],
    serve:[[45,'g','poha'],[2,'','eggs'],[15,'g','peanuts']],
    method:['Rinse the poha, drain and let it soften 5 minutes.','Temper mustard seeds, curry leaves and peanuts in oil; add onion and peas.','Add turmeric, salt and poha; toss on low heat. Finish with lemon and coriander.','Serve with boiled or fried eggs.'],
    swaps:['Sprouted-moong poha for more protein','Tofu cubes instead of eggs','Add grated carrot for fibre']}),
  RC({id:'oats',name:'Overnight Oats + Chia',cat:'breakfast',cuisine:'Make-ahead',tags:['oats','chia','no-sugar','make-ahead'],
    upgrade:'Greek-yogurt base + chia pushes protein past plain oats.',
    ing:[['oats',50,'g'],['greek',150,'g'],['milk',100,'ml'],['chia',10,'g'],['berries',60,'g']],
    serve:[[50,'g','oats'],[150,'g','Greek yogurt'],[60,'g','berries']],
    method:['Stir oats, Greek yogurt, milk, chia and cinnamon together in jars (sweeten with monkfruit if wanted).','Refrigerate overnight.','Top with berries in the morning.'],
    swaps:['Stir in ½ scoop whey for +12g protein','Soy milk to go dairy-free','Swap berries for chopped apple']}),
  RC({id:'pancake',name:'Banana-Oat Protein Pancakes',cat:'breakfast',cuisine:'Fusion',tags:['pancake','banana','whey','no-sugar'],
    upgrade:'Whey + egg folded into the batter; no syrup.',
    ing:[['oats',40,'g'],['banana',0.5,''],['egg',1,''],['whey',15,'g'],['milk',50,'ml'],['berries',40,'g'],['oil',3,'g']],
    serve:[[3,'','pancakes'],[40,'g','berries']],
    method:['Blend oats, banana, eggs, whey, milk and a pinch of baking powder.','Cook small pancakes on a lightly oiled pan over medium-low heat; flip when bubbles form.','Top with berries — no syrup (monkfruit or allulose syrup if wanted).'],
    swaps:['Savoury besan-veg chilla instead','Cottage cheese in the batter','Peanut-butter drizzle for the guys']}),
  RC({id:'dosa',name:'Masala Egg Dosa + Sambar',cat:'breakfast',cuisine:'South Indian',tags:['dosa','egg','sambar'],
    upgrade:'Egg smeared on the dosa + lentil sambar = double protein.',
    ing:[['dosabatter',150,'g'],['egg',1,''],['toor',25,'g'],['mixveg',50,'g'],['oil',5,'g']],
    serve:[[2,'','dosa'],[1,'','egg'],[150,'ml','sambar']],
    method:['Pressure-cook toor dal with turmeric; simmer with vegetables, tamarind and sambar powder.','Spread dosa batter thin on a hot tawa; crack an egg on top and spread it over.','Drizzle a little oil, cook till crisp and fold.','Serve hot with sambar.'],
    swaps:['Plain dosa with extra sambar','Paneer filling instead of egg','Ragi or oats dosa batter for more fibre']}),
  RC({id:'paratha',name:'Paneer Paratha + Curd',cat:'breakfast',cuisine:'Punjabi',tags:['paneer','paratha','curd'],
    upgrade:'Dense paneer stuffing, cooked with just a smear of ghee.',
    ing:[['atta',60,'g'],['paneer',50,'g'],['curd',100,'g'],['ghee',5,'g']],
    serve:[[2,'','parathas'],[50,'g','paneer'],[100,'g','curd']],
    method:['Knead atta into a soft dough; rest 15 minutes.','Mix grated paneer with chilli, coriander, ajwain and salt.','Stuff, seal and roll gently.','Cook on the tawa with a light smear of ghee till spotted; serve with curd.'],
    swaps:['Low-fat paneer for Dvija','Tofu-scramble stuffing','Methi or palak worked into the dough']}),
  RC({id:'avotoast',name:'Avocado Toast + Eggs',cat:'breakfast',cuisine:'Fusion',tags:['avocado','egg','toast'],
    upgrade:'Two eggs carry the protein; avocado carries the good fats.',
    ing:[['bread',2,''],['avocado',0.33,''],['egg',2,''],['tomato',30,'g']],
    serve:[[2,'slice','toast'],[50,'g','avocado'],[2,'','eggs']],
    method:['Toast the bread; mash avocado with lemon, salt and chilli flakes.','Fry or poach the eggs.','Assemble with sliced tomato.'],
    swaps:['Cottage-cheese base (lower fat)','Tofu scramble on top','Sourdough instead of whole-grain']}),
  RC({id:'parfait',name:'Greek Yogurt Berry Parfait',cat:'breakfast',cuisine:'Make-ahead',tags:['greek','berries','no-sugar','make-ahead'],
    upgrade:'Greek yogurt is ~3× the protein of regular curd.',
    ing:[['greek',200,'g'],['berries',80,'g'],['oats',30,'g'],['chia',5,'g'],['almondbutter',10,'g']],
    serve:[[200,'g','Greek yogurt'],[80,'g','berries'],[30,'g','toasted oats']],
    method:['Dry-toast the oats in a pan till fragrant; cool.','Layer yogurt, berries, oats and chia in a glass.','Finish with a drizzle of almond butter.'],
    swaps:['Hung curd if Greek is unavailable','Roasted chana instead of oats','Add ½ scoop whey to the yogurt']}),
  RC({id:'rajgira',name:'Rajgira Paratha + Curd',cat:'breakfast',farali:true,cuisine:'Gujarati',tags:['farali','vrat','rajgira','thursday'],
    upgrade:'Amaranth flour is a farali grain with real protein and iron.',
    ing:[['rajgira',60,'g'],['potato',50,'g'],['curd',150,'g'],['ghee',5,'g']],
    serve:[[2,'','rajgira parathas'],[150,'g','curd']],
    method:['Mash boiled potato into rajgira flour with sendha namak and green chilli; knead to a soft dough.','Pat or roll between sheets of parchment.','Cook on a tawa with a little ghee; serve with curd.'],
    swaps:['Singhara flour instead of rajgira','Add grated paneer to the dough','Sweet-potato binder instead of potato']}),

  /* ---------- lunch & dinner mains ---------- */
  RC({id:'dalrice',name:'Dal + Brown Rice + Curd',cat:'main',leftover:true,cuisine:'Gujarati',tags:['dal','rice','lentil','packable'],
    upgrade:'Brown rice for fibre; curd on the side completes the protein.',
    ing:[['toor',45,'g'],['brownrice',50,'g'],['curd',100,'g'],['onion',20,'g'],['tomato',40,'g'],['cucumber',60,'g'],['ghee',5,'g']],
    serve:[[200,'g','dal'],[150,'g','brown rice'],[100,'g','curd']],
    method:['Pressure-cook toor dal with turmeric (3 whistles); cook the brown rice separately (or pot-in-pot in the Instant Pot, 22 min).','Temper cumin, garlic, onion and tomato in ghee; pour into the dal and simmer 5 minutes.','Serve with curd and cucumber salad. Pack tomorrow’s lunch portions before serving.'],
    swaps:['Mixed dal (toor + moong + masoor)','Millet or quinoa instead of rice','Stir spinach into the dal']}),
  RC({id:'chole',name:'Chole + Brown Rice',cat:'main',leftover:true,cuisine:'Punjabi',tags:['chole','chickpea','brown-rice','packable'],
    upgrade:'Chickpeas bring fibre and protein; brown rice keeps it low-GI.',
    ing:[['chana',60,'g'],['brownrice',45,'g'],['curd',75,'g'],['onion',30,'g'],['tomato',50,'g'],['oil',5,'g']],
    serve:[[220,'g','chole'],[140,'g','brown rice'],[75,'g','raita']],
    method:['Soak chana overnight; pressure-cook till very soft (Instant Pot 35 min).','Cook onion, ginger-garlic and tomato with chole masala; add chana and simmer 15 minutes.','Serve with brown rice and cucumber raita. Pack tomorrow’s lunch portions.'],
    swaps:['Kala chana instead','Add spinach or methi','Cauliflower rice for Dvija (lower carb)']}),
  RC({id:'rajma',name:'Rajma + Brown Rice',cat:'main',leftover:true,cuisine:'Punjabi',tags:['rajma','rice','beans','packable'],
    upgrade:'Kidney beans + rice = a complete amino profile.',
    ing:[['rajma',60,'g'],['brownrice',45,'g'],['onion',30,'g'],['tomato',50,'g'],['oil',5,'g']],
    serve:[[220,'g','rajma'],[140,'g','brown rice']],
    method:['Soak rajma overnight; pressure-cook till creamy (Instant Pot 30 min).','Simmer in an onion-tomato gravy with garam masala.','Serve with brown rice and salad. Pack tomorrow’s lunch portions.'],
    swaps:['Mixed beans','Boiled egg on the side','Jeera millet instead of rice']}),
  RC({id:'palak',name:'Palak Paneer + Roti',cat:'main',leftover:true,cuisine:'Punjabi',tags:['palak','paneer','spinach'],
    upgrade:'Spinach for iron, paneer for protein — no cream needed.',
    ing:[['spinach',150,'g'],['paneer',75,'g'],['onion',30,'g'],['tomato',40,'g'],['atta',40,'g'],['oil',5,'g']],
    serve:[[200,'g','palak paneer'],[1.5,'','roti']],
    method:['Blanch spinach 2 minutes, plunge into cold water and blend smooth.','Sauté cumin, onion, ginger-garlic and tomato; add the purée and spices and simmer.','Fold in paneer cubes (tofu works too) and finish with a spoon of milk instead of cream.','Serve with fresh roti. Pack tomorrow’s lunch portions.'],
    swaps:['Tofu instead of paneer (lower fat)','Add green peas','Palak-methi version']}),
  RC({id:'mattar',name:'Paneer Mattar + Roti',cat:'main',leftover:true,cuisine:'North Indian',tags:['paneer','peas','roti'],
    upgrade:'Paneer + peas layer two protein sources into one gravy.',
    ing:[['paneer',70,'g'],['peas',60,'g'],['onion',30,'g'],['tomato',50,'g'],['atta',40,'g'],['oil',5,'g']],
    serve:[[200,'g','paneer mattar'],[1.5,'','roti']],
    method:['Make an onion-tomato gravy with ginger, garlic and spices.','Add peas and simmer 5 minutes; add paneer and simmer 5 more.','Serve with roti. Pack tomorrow’s lunch portions.'],
    swaps:['Low-fat paneer for Dvija','Tofu with peas','Add mushrooms']}),
  RC({id:'pinkpasta',name:'Pink Pasta with Tofu + Broccoli',cat:'main',leftover:true,cuisine:'Fusion',tags:['pasta','tofu','broccoli'],
    upgrade:'Tofu and whole-wheat pasta so protein leads, not carbs.',
    ing:[['pasta',50,'g'],['tofu',100,'g'],['broccoli',80,'g'],['passata',80,'g'],['milk',50,'ml'],['oil',5,'g']],
    serve:[[50,'g','pasta (dry)'],[100,'g','tofu'],[80,'g','broccoli']],
    method:['Boil the pasta al dente; blanch broccoli in the same water for the last 2 minutes.','Press, cube and pan-sear the tofu till golden.','Simmer passata with garlic and chilli; stir in milk for a pink sauce.','Toss everything together. Pack tomorrow’s lunch portions.'],
    swaps:['Paneer instead of tofu','Lentil pasta for more protein','Plain red sauce']}),
  RC({id:'friedrice',name:'Tofu Fried Rice + Baked Gobi Manchurian',cat:'main',leftover:true,cuisine:'Indo-Chinese',tags:['indo-chinese','tofu','fried-rice','gobi'],
    upgrade:'Brown rice, loads of tofu and veg; the manchurian is oven-baked, not fried.',
    ing:[['brownrice',45,'g'],['tofu',100,'g'],['cauliflower',120,'g'],['capsicum',40,'g'],['onion',20,'g'],['besan',10,'g'],['oil',7,'g']],
    serve:[[180,'g','fried rice'],[120,'g','gobi manchurian']],
    method:['Cook the brown rice a day ahead if you can; cold rice fries best.','Toss cauliflower florets in a thin besan batter; bake at 220°C for 20 minutes, then coat in manchurian sauce.','Stir-fry tofu and vegetables on high heat; add rice, soy sauce and pepper.','Serve together. Pack tomorrow’s lunch portions.'],
    swaps:['Paneer manchurian','Cauliflower-rice base for Dvija','Add egg for egg-fried rice']}),
  RC({id:'khichdi',name:'Moong Khichdi + Kadhi',cat:'main',leftover:true,cuisine:'Gujarati',tags:['khichdi','kadhi','moong','comfort'],
    upgrade:'Moong-heavy khichdi with a curd kadhi for protein.',
    ing:[['brownrice',30,'g'],['moong',40,'g'],['mixveg',40,'g'],['curd',120,'g'],['besan',10,'g'],['ghee',5,'g']],
    serve:[[250,'g','khichdi'],[150,'ml','kadhi']],
    method:['Pressure-cook rice, moong dal and vegetables with turmeric to a soft khichdi.','Whisk curd and besan with water; simmer into kadhi with a cumin-curry-leaf tempering.','Serve khichdi with a small spoon of ghee and the kadhi.'],
    swaps:['Masala khichdi with more veg','Bajra or quinoa khichdi','Low-fat curd kadhi for Dvija']}),
  RC({id:'mexican',name:'Mexican Bean Bowl',cat:'main',leftover:true,cuisine:'Fusion',tags:['mexican','beans','avocado'],
    upgrade:'Pinto + black beans double the protein of plain rice.',
    ing:[['pinto',30,'g'],['blackbean',30,'g'],['brownrice',30,'g'],['tomato',40,'g'],['onion',20,'g'],['capsicum',30,'g'],['corn',30,'g'],['avocado',0.2,''],['feta',15,'g'],['oil',4,'g']],
    serve:[[200,'g','beans'],[100,'g','brown rice'],[30,'g','avocado']],
    method:['Pressure-cook the soaked beans; simmer with tomato, cumin, paprika and oregano.','Cook the brown rice; sauté corn, onion and capsicum.','Build bowls; top with avocado, feta, salsa and lime. Pack tomorrow’s lunch without the avocado.'],
    swaps:['Rajma instead of pinto','Lettuce cups for Dvija','Add scrambled egg or paneer']}),
  RC({id:'misal',name:'Sprout Misal Pav',cat:'main',leftover:true,cuisine:'Maharashtrian',tags:['misal','sprout','pav'],
    upgrade:'Sprouted moong + matki is protein-dense street food.',
    ing:[['sprouts',120,'g'],['matki',25,'g'],['onion',30,'g'],['tomato',40,'g'],['pav',2,''],['oil',5,'g']],
    serve:[[250,'g','misal'],[2,'','pav']],
    method:['Cook sprouts and matki until just soft.','Make the spicy tari with onion, tomato, coconut and misal masala; add the sprouts.','Top with onion and coriander (go easy on farsan); serve with pav.'],
    swaps:['Skip farsan for Dvija','Extra sprouts for protein','Multigrain pav']}),
  RC({id:'makhni',name:'Light Dal Makhni + Brown Rice',cat:'main',leftover:true,cuisine:'Punjabi',tags:['dal','makhni','lentil'],
    upgrade:'Milk replaces cream; the lentils already carry the protein.',
    ing:[['urad',40,'g'],['rajma',15,'g'],['tomato',60,'g'],['milk',40,'ml'],['butter',5,'g'],['brownrice',40,'g']],
    serve:[[220,'g','dal makhni'],[120,'g','brown rice']],
    method:['Soak urad and rajma overnight; pressure-cook till very soft (Instant Pot 40 min).','Simmer with tomato purée, ginger, garlic and a little butter for 20 minutes.','Finish with milk instead of cream; serve with brown rice or roti.'],
    swaps:['Extra rajma for protein','Serve with roti','Skip butter for Dvija']}),
  RC({id:'pavbhaji',name:'Protein Pav Bhaji',cat:'main',leftover:true,cuisine:'Maharashtrian',tags:['pav-bhaji','veg','rajma'],
    upgrade:'Rajma mashed into the bhaji; whole-wheat pav; a fraction of the butter.',
    ing:[['potato',60,'g'],['cauliflower',80,'g'],['peas',40,'g'],['capsicum',40,'g'],['rajma',20,'g'],['tomato',60,'g'],['onion',20,'g'],['pav',2,''],['butter',5,'g']],
    serve:[[250,'g','bhaji'],[2,'','pav']],
    method:['Pressure-cook potato, cauliflower, peas and soaked rajma.','Cook onion, capsicum and tomato with pav bhaji masala; mash in the vegetables.','Toast the pav with a light brush of butter; serve with onion and lemon.'],
    swaps:['More cauliflower, less potato for Dvija','Paneer bhurji on top','Multigrain pav']}),
  RC({id:'pizza',name:'Whole-Wheat Paneer Veggie Pizza',cat:'main',cuisine:'Fusion',tags:['pizza','paneer','wholewheat'],
    upgrade:'Whole-wheat base, part-skim cheese, loaded with veg and paneer.',
    ing:[['pizzabase',100,'g'],['mozzarella',40,'g'],['paneer',30,'g'],['capsicum',30,'g'],['onion',20,'g'],['mushroom',40,'g'],['olives',10,'g'],['passata',40,'g']],
    serve:[[2,'slice','pizza (½ base)']],
    method:['Sauce the base; add cheese, paneer and vegetables.','Bake at 230°C for 10–12 minutes until the crust crisps.','Slice and pair with a green salad.'],
    swaps:['Thinner cheese, more veg for Dvija','Tofu-ricotta to go dairy-free','Cauliflower crust (lower carb)']}),
  RC({id:'subway',name:'Loaded Paneer Sub',cat:'main',cuisine:'Fusion',tags:['sandwich','paneer','packable'],
    upgrade:'Grilled paneer so the filling outweighs the bread.',
    ing:[['subroll',1,''],['paneer',60,'g'],['spinach',15,'g'],['tomato',30,'g'],['onion',15,'g'],['capsicum',25,'g'],['olives',8,'g'],['greek',30,'g']],
    serve:[[1,'','sub roll'],[60,'g','grilled paneer']],
    method:['Grill spiced paneer slices on a tawa.','Split the roll; spread Greek-yogurt mint dressing.','Load with paneer and vegetables.'],
    swaps:['Egg filling for leaner protein','Wrap instead of a roll','Hummus spread']}),
  RC({id:'sabudana',name:'Sabudana Khichdi + Curd',cat:'main',farali:true,cuisine:'Gujarati',tags:['farali','vrat','sabudana','thursday','peanut'],
    upgrade:'Fasting food — peanuts and curd carry the protein.',
    ing:[['sabudana',60,'g'],['peanuts',20,'g'],['potato',60,'g'],['curd',150,'g'],['ghee',5,'g']],
    serve:[[200,'g','sabudana khichdi'],[150,'g','curd']],
    method:['Soak sabudana 4–6 hours till each pearl is soft; drain well.','Temper cumin and green chilli in ghee; add diced boiled potato and crushed peanuts.','Add sabudana and sendha namak; cook on low till translucent. Serve with curd.'],
    swaps:['More peanuts for protein','Rajgira chilla instead','Sweet potato instead of potato']}),
  RC({id:'samo',name:'Samo Millet Khichdi + Peanut Curd',cat:'main',farali:true,cuisine:'Gujarati',tags:['farali','vrat','millet','thursday'],
    upgrade:'Barnyard millet has ~5× the protein and fibre of sabudana.',
    ing:[['samo',50,'g'],['peanuts',20,'g'],['potato',40,'g'],['curd',150,'g'],['ghee',5,'g']],
    serve:[[220,'g','samo khichdi'],[150,'g','curd']],
    method:['Rinse samo; cook with 3× water, diced potato and sendha namak (Instant Pot 6 min).','Temper cumin, green chilli and crushed peanuts in ghee; stir through.','Serve with curd mixed with roasted peanut powder.'],
    swaps:['Rajgira instead of samo','Sweet potato instead of potato','Add paneer cubes for protein']}),
];

/* Fixed items everyone has every day (per person). */
const FIXED = {
  drink: {m3:'mdrink', m1:'mdrink', m2:'mdrink'},
  shake: {m3:'shake_lite', m1:'shake_gain', m2:'shake_gain'},
};
const rec = id => RECIPES.find(r=>r.id===id);
